### ISSUE TITLE
Failed to run the command:  nsh> mavlink -d /dev/ttyACM0 

### ISSUE THREAD

**Issue by yajingwang94** [mavlink/c_uart_interface_example#21]
Hi. I want to learn about the communication mechanism between pixhawk and ubuntu PC(especially with ROS), but I failed to run the command mentioned in the title. Could you please give me some instructions? 
It reported that "bash: mavlink: Is a directory."
Thanks.

**Comment by JMare** [comment]
Sounds like you ran the command in bash on your computer.

Make sure to follow the steps under "login to pixhawk shell"
