### ISSUE TITLE
Replace send_quad_commands example with offboard control example

### ISSUE THREAD

**Issue by LorenzMeier** [mavlink/c_uart_interface_example#6]
@julianoes @thomasgubler Issue to track the relevant discussion here:
https://groups.google.com/forum/#!topic/px4users/IC1iz_TsL_Y

For all people interested to send high-rate set points offboard: What needs to be done is:

  * Update the files in the mavlink folder with this: https://github.com/mavlink/c_library
  * Replace the send_quads message with the appropriate SET_ATTITUDE_TARGET and SET_POSITION_TARGET messages: http://mavlink.org/messages/common#SET_POSITION_TARGET_LOCAL_NED
  * Provide a decent README.md how to configure and operate the system to make this work

Having an example ready that works out of the box would be a huge step forward.

**Comment by aerialhedgehog** [comment]
I think we can close this issue
